version: "3.8"
services:
  backend:
    image: clementcaquet/backend:1
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    image: clementcaquet/frontend:1
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend


