version: '3.8'

services:
  backend:
    image: clementcaquet/backend:1
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=postgres  # Set the superuser password for PostgreSQL
      - DB_NAME=mydatabase
    depends_on:
      - database

  frontend:
    image: clementcaquet/frontend:1
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  database:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: admin        # Set the username
      POSTGRES_PASSWORD: postgres  # Set the superuser password
      POSTGRES_DB: mydatabase     # Set the default database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data across container restarts

volumes:
  postgres_data: {}
